version: 2

sources:

  - name: vocabulary
    database: iceberg
    schema: vocabulary
    tables:
      - name: concept
        description: Tabla de conceptos del vocabulario OMOP.
      - name: concept_relationship
        description: Tabla de relaciones entre conceptos del vocabulario OMOP.
  - name: mimic
    description: Tablas crudas de MIMIC-IV cargadas en Iceberg (schema mimic-bronze).
    database: iceberg
    schema: mimic-bronze
    tables:
      - name: patients
        description: Información demográfica de pacientes.
        columns:
          - name: subject_id
            description: Identificador único del paciente.
          - name: gender
          - name: anchor_age
          - name: anchor_year
          - name: anchor_year_group
          - name: dod

      - name: admissions
        description: Ingresos hospitalarios.
        columns:
          - name: subject_id
          - name: hadm_id
            description: Identificador único del ingreso.
          - name: admittime
          - name: dischtime
          - name: deathtime
          - name: admission_type
          - name: admit_provider_id
          - name: admission_location
          - name: discharge_location
          - name: insurance
          - name: language
          - name: marital_status
          - name: race
          - name: edregtime
          - name: edouttime
          - name: hospital_expire_flag

      - name: diagnoses_icd
        description: Diagnósticos codificados con ICD-9/ICD-10.
        columns:
          - name: subject_id
          - name: hadm_id
          - name: seq_num
          - name: icd_code
          - name: icd_version

