# Partimos de la imagen base de Airflow
FROM apache/airflow:2.9.3-python3.11

# Usamos el usuario airflow para instalar providers y dbt
USER airflow

# Instalamos los providers y las librerías de dbt con versiones compatibles
RUN pip install --no-cache-dir \
    apache-airflow-providers-postgres \
    apache-airflow-providers-amazon \
    psycopg2-binary \
    pandas \
    dbt-core==1.7.1 \
    dbt-trino==1.7.1

# Copiar el script de inicialización
USER root
COPY init-airflow.sh /init-airflow.sh
RUN chmod +x /init-airflow.sh
USER airflow